apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-cluster
  namespace: techblog
spec:
  serviceName: redis-service
  replicas: 3
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:6-alpine
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: redis-data
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: redis-data
      spec:
        storageClassName: fast-storage
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi